"""add analysis fields (keywords, topic, summaries)

Revision ID: 3254d52cf60f
Revises: 377c39b58dcd
Create Date: 2025-09-25 19:01:47.994863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3254d52cf60f'
down_revision = '377c39b58dcd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_articles_simhash64'), ['simhash64'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_articles_simhash64'))

    # ### end Alembic commands ###
