"""add preprocess fields

Revision ID: 377c39b58dcd
Revises: 7c87b9298281
Create Date: 2025-09-25 18:31:56.953303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '377c39b58dcd'
down_revision = '7c87b9298281'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content_clean', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('simhash64', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('is_duplicate', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('duplicate_of_id', sa.Integer(), nullable=True))

        # 이름을 지정한 FK 추가
        batch_op.create_foreign_key(
            'fk_articles_duplicate_of_id',  # ← FK 이름(아무거나 OK, 중복만 아니면)
            'articles',                     # 참조 테이블
            ['duplicate_of_id'],            # 현재 테이블 FK 컬럼
            ['id']                          # 참조 테이블 PK 컬럼
     )


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.drop_constraint('fk_articles_duplicate_of_id', type_='foreignkey')
        batch_op.drop_column('duplicate_of_id')
        batch_op.drop_column('is_duplicate')
        batch_op.drop_column('simhash64')
        batch_op.drop_column('content_clean')

    # ### end Alembic commands ###
