"""add analysis fields (keywords_json, topic_id, summary_gen, summary_ko)

Revision ID: 6aeeff529467
Revises: 3254d52cf60f
Create Date: 2025-09-25 19:40:23.637587

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6aeeff529467'
down_revision = '3254d52cf60f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('keywords_json', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('topic_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('summary_gen', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('summary_ko', sa.Text(), nullable=True))
        batch_op.create_index(batch_op.f('ix_articles_topic_id'), ['topic_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_articles_topic_id'))
        batch_op.drop_column('summary_ko')
        batch_op.drop_column('summary_gen')
        batch_op.drop_column('topic_id')
        batch_op.drop_column('keywords_json')

    # ### end Alembic commands ###
